# Introduction to Machine Learning

To apply today's course, we will analyze together examples of projects involving the development of Machine Learning algorithms. We will then see a complete case of ML including data cleaning, modeling and evaluation.

Up to you! And remember, don't get stuck, search, ask questions, have fun! We are all here to learn and practice.

## 1) Application case

In this exercise, you have minutes of kick-off meetings for projects involving machine learning. You need to determine:
- Are we talking about a supervised or unsupervised problem?
- Is the data structured or unstructured?
- Is it a regression or classification problem? Neither of the two ?
- What are the features and what is the target?
- What other feature ideas do you have in mind for the given problem?

Feel free to brainstorm as a group.

a) Sales prediction: The goal of the project is to predict the sales of a perfume shop to adjust the stock accordingly. The shop organizes events both in person and on social networks. Its sales are very sensitive to the season and the weather. The company can easily provide its sales data and the planning of its physical events, on the other hand we must go and retrieve the other information if necessary.

b) Detection of the risk of default: The aim of the project is to detect if a person is at risk of not being able to repay his loan. This will save time to focus only on the most contentious cases. Loan data and subscriber data are already in the database.

c) Customer segmentation: The company delivers vegetable baskets. The goal of the project is to get to know their customers better by grouping them according to their characteristics. They will be able to think about how to improve the experience of each customer profile. They send us their basket sales data and we asked for whatever information they could have on their customers (in progress).

d) Fracture diagnostics: The company is a radiology practice and wishes to have an algorithm for detecting the type of fracture. There are 7 types of fractures (transverse, longitudinal, displaced oblique, non-displaced oblique, greenstick, comminuted, spiral). From the radio, it is not always obvious and some are rare. This is why based on all the x-rays and their confirmed diagnoses, we want to develop an algorithm.

## 2) Data Cleaning

A jewelry company comes up with an idea to help sales associates identify customers with the highest purchasing potential. For this, according to their internal criteria, they were able to collect purchasing information from their customers and assign them a category between *occasional*, *frequent* and *vip* . Vip designates the most important customers, *frequent* the regulars and occasional the remaining customers.

As a Data Analyst, you are asked to prepare data for the creation of a machine learning algorithm. Thus, for customers that are not yet categorized, it will suffice to use the algorithm to predict their categories and thus adapt the level of service accordingly.

#### Identifying the problem

a) Download the `customer_segmentation.csv` file at this [address](https://drive.google.com/file/d/1vnwPLcHcsrbZScKEG8yD4oPOVUyGHDTB/view?usp=sharing) and load the data in a `df` variable

The data has 9 columns:
- country: the customer's country of origin
- customer_type: the importance category of the customer
- average_basket: the average number of items purchased by the customer rounding up
- average_price: the average price spent by the customer rounding up
- visit_number: the number of visits made by the customer to the store
- age: the age of the customer
- gender: the customer's gender
- hobbies: leisure activities declared by the client
- customer_id: the internal unique identifier of the customer

b) Qualify the type of machine learning problem you are facing and identify the features and the target variable.

c) What do you think of the `customer_id` column as a feature? Is it useful in your opinion? (No code to do)

d) Delete the `customer_id` column.

#### Removing nonsensical values

e) From the .info() method of a Dataframe, determine which column(s) have missing information? What are text (object) type columns?

f) Before dealing with missing values, it is always important to check the orders of magnitude of the numerical columns and see if there are any outliers. From a Dataframe's .describe() method, determine outlier cases

g) [more difficult] Delete rows whose `average_price` column values ​​are absurd in your opinion. Consider using panda masking techniques. **Be careful not to delete the null values ​​that we will then process** As a reminder, to determine the null values ​​of the column we can use `df.average_price.isnull()`

#### Handling missing values

h) To replace missing values, one must first ensure that they do not represent a large part of the data. Calculate the proportion of missing values ​​per column.

i) What do you think of the `hobbies` column? Can it be kept?

j) Delete the `hobbies` column

k) What strategy(ies) can you consider to replace missing values ​​in the `average_price`, `age` and `gender` columns?

l) Replace the missing values ​​in the `gender` column with the mode. For that, see how to calculate mode and then parse pandas [fillna](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.fillna.html) function.

m) Replace the missing values ​​in the `average_price` and `age` columns with their respective means.

n) Verify that your Data Frame no longer contains any missing values.

#### Separation between features and target

o) Put the features in an `X` variable and the target column in a `y` variable

#### Convert text to numeric columns

#### The target variable

o) Transform `y` to values ​​0, 1 and 2 with sklearn's [LabelEncoder](https://scikit-learn.org/stable/modules/generated/sklearn.preprocessing.LabelEncoder.html) tool. Check and view classes.

In [ ]:
from sklearn.preprocessing import LabelEncoder

# to complete

[1 1 1 ... 1 1 1]
['frequent' 'occasional' 'vip']


The classes are transformed by their index in alphabetical order, 0 for the first, 1 for the next ....

#### Features

p) In a new `X_dummy` variable, transform the text of the `country` and `gender` columns with the tool [OneHotEncoder](https://scikit-learn.org/stable/modules/generated/sklearn.preprocessing. OneHotEncoder.html#sklearn.preprocessing.OneHotEncoder) from sklearn. Then display the categories. **Add sparse=False in parameters of OneHotEncoder()**

In [ ]:
from sklearn.preprocessing import OneHotEncoder

# to complete

[[0. 1. 0. 1. 0.]
 [0. 0. 1. 0. 1.]
 [1. 0. 0. 0. 1.]
 ...
 [1. 0. 0. 1. 0.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]]
[array(['fr', 'it', 'uk'], dtype=object), array(['female', 'male'], dtype=object)]


q) What does this statement do?

In [ ]:
dummy_cols = np.concatenate((onehotencoder.categories_[0], onehotencoder.categories_[1]), axis=None)
print(dummy_cols)

['fr' 'it' 'uk' 'female' 'male']


r) Transform X_dummy into a DataFrame object with the correct column names using the previous question.

#### Normalization

Now that our data no longer contains any text type data, we will normalize our numeric features.

s) In an `X_num` variable, normalize the values ​​of the `average_basket`, `average_price`, `visit_number` and `age` columns. You can use the [StandardScaler](https://scikit-learn.org/stable/modules/generated/sklearn.preprocessing.StandardScaler.html) tool from sklearn.

In [ ]:
from sklearn.preprocessing import StandardScaler

# to complete

t) Transform X_num into a DataFrame with the correct column names.

#### Reconstruction of transformed features

s) Group the `X_dummy` and `X_num` variables into an `X` DataFrame with the correct column names. You can use pandas [concat](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.concat.html) function. **Pay attention to the axis parameter** then display the result.

In [ ]:
X = pd.concat([X_dummy, X_num], axis=1)

You should get the following result:

In [ ]:
X

,fr,it,uk,female,male,average_basket,average_price,visit_number,age
0,0.0,1.0,0.0,1.0,0.0,-0.170249,-1.072076e+00,-0.552283,-9.022601e-01
1,0.0,0.0,1.0,0.0,1.0,0.472694,3.088094e-01,-0.748189,1.085567e+00
2,1.0,0.0,0.0,0.0,1.0,-0.813192,-8.079086e-01,-0.552283,8.867840e-01
3,1.0,0.0,0.0,0.0,1.0,-0.813192,-7.942839e-01,-0.356378,-3.059120e-01
4,1.0,0.0,0.0,0.0,1.0,-0.813192,-8.185056e-01,-0.552283,2.904360e-01
5,1.0,0.0,0.0,0.0,1.0,0.472694,1.206523e+00,1.406769,4.892187e-01
6,1.0,0.0,0.0,0.0,1.0,-0.813192,-7.137975e-01,-0.748189,-1.299825e+00
7,0.0,0.0,1.0,0.0,1.0,-0.170249,1.839166e-01,-0.552283,-1.498608e+00
8,1.0,0.0,0.0,0.0,1.0,-0.170249,-2.294734e-16,-0.748189,-1.101043e+00
9,1.0,0.0,0.0,1.0,0.0,-0.813192,-7.935270e-01,-0.552283,1.582523e+00


**BRAVO** You have just cleaned the data!! They are now ready to be used to build a machine learning algorithm.

t) Summarize the steps taken and lessons learned as a memo.

- removal of unnecessary columns (customer_id)
- removal of absurd values ​​(negative values ​​of average_price)
- dummification of textual values ​​with labelencoder for target (client_type) and onehotencoder for features (country, gender)
- normalization of numerical features (average_basket, average_price, visit_number, age)
- concatenation of results in a single variable X

## 3) Modeling

u) From function [train_test_split](https://scikit-learn.org/stable/modules/generated/sklearn.model_selection.train_test<_>split.html) from sklearn and from `X` and `y`, generate the dataframes `X_train`, `X_test`, `y<_>train`, `y_test`. The training sample (train) will represent 70% of the initial data.

In [ ]:
from sklearn.model_selection import train_test_split

# to complete

v) From sklearn, create a model like [DecisionTreeClassifier](https://scikit-learn.org/stable/modules/generated/sklearn.tree.DecisionTreeClassifier.html#sklearn.tree.DecisionTreeClassifier.score) and train le on your training data with the `fit` method.

In [ ]:
from sklearn.tree import DecisionTreeClassifier

# to complete

DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=None,
                       max_features=None, max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, presort=False,
                       random_state=None, splitter='best')

w) From the `score` method of the model, display the score on the training data and the test data. What do you notice ?

## 4) Prediction

x) Download the file `customer_segmentation_new.csv` at this [address](https://drive.google.com/file/d/1dbveJ9Urk7KQ4RaDynXD4wKLpNZ6U6yY/view?usp=sharing) in a variable ` df_new`. This file corresponds to new customers who do not yet have categories.
- Apply the same transformations as before to obtain a dataframe `X_new` which will correspond to the transformed version of `df_new` (Help yourself from your answer to question t so as not to forget steps )
- From X_new and your previously trained model, predict the vector `y_predict` corresponding to the categorization of each of these new customers

**Warning**: It is important to keep the same transformations as in training. For example, an imputation by the mean should be imputed by the same mean as in training and not a new mean. Similarly for transformations requiring a `fit_transform`, in the prediction phase only the `transform` is necessary.

In [ ]:
# to complete

y_predict

array([0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2,
       1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1,
       2, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0,
       0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 0, 0, 2, 1, 1,
       1, 1, 2, 1, 0, 1, 2, 1, 1, 0, 1, 2, 0, 1, 1, 1, 0, 1, 1, 0, 2, 1,
       1, 1, 1, 1, 1, 0, 1, 2, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 0,
       0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 2, 1, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1,
       1, 1, 1, 1, 0, 2, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 2, 1, 2, 1, 1, 1,
       0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 2, 1, 1, 1, 2, 1, 0, 2, 0, 0, 1, 1,
       2, 0, 1, 1, 1, 1, 0, 2, 1, 2, 1, 1, 0, 0, 1, 0, 1, 1, 1, 1, 0, 1,
       1, 0, 1, 1, 1, 1, 2, 1, 1, 1, 1, 1, 0, 1, 2, 2, 1, 1, 1, 1, 1, 0,
       1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1,
       0, 1, 0, 0, 1, 1, 1, 2, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 2, 1,
       1, 2, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1,

## 5) [Bonus] Optimization

y) From sklearn's [GridSearchCV](https://scikit-learn.org/stable/modules/generated/sklearn.model_selection.GridSearchCV.html) class, perform a grid search of your previous model .
You will perform a grid search with a 3 fold cross validation parameter and the hyperparameter grid will be as follows.

`params = {
    'min_samples_split': [0.001, 0.01, 0.1, 0.2, 0.5],
    "max_depth": [2, 5,10, None]
}`

In [ ]:
from sklearn.model_selection import GridSearchCV

params = {
    'min_samples_split': [0.001, 0.01, 0.1, 0.2, 0.5],
    "max_depth": [2, 5,10,None]
}

# to complete

GridSearchCV(cv=3, error_score='raise-deprecating',
             estimator=DecisionTreeClassifier(class_weight=None,
                                              criterion='gini', max_depth=None,
                                              max_features=None,
                                              max_leaf_nodes=None,
                                              min_impurity_decrease=0.0,
                                              min_impurity_split=None,
                                              min_samples_leaf=1,
                                              min_samples_split=2,
                                              min_weight_fraction_leaf=0.0,
                                              presort=False, random_state=None,
                                              splitter='best'),
             iid='warn', n_jobs=None,
             param_grid={'max_depth': [2, 5, 10, None],
                         'min_samples_split': [0.001, 0.01, 0.1, 0.2, 0.5]},
   

z) Display the best hyperparameters determined by the grid search.

In [ ]:
my_grid_tree_classifier.best_params_

{'max_depth': 10, 'min_samples_split': 0.001}

a_bis) From the `score` method of the grid-searched model, display the score on the training data and the test data. What do you notice about the score of the non-grid-searched model?